import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('image.jpg')
rows, cols, ch = img.shape

pts1 = np.float32([[50, 50], [200, 50], [50, 200]])
pts2 = np.float32([[10, 100], [200, 50], [100, 250]])

M = cv2.getAffineTransform(pts1, pts2)
dst = cv2.warpAffine(img, M, (cols, rows))

plt.subplot(121)
plt.imshow(img)
plt.title('Input')
plt.subplot(122)
plt.imshow(dst)
plt.title('Output (Affine)')
plt.show()

M = cv2.getRotationMatrix2D((cols/2, rows/2), 90, 1)
dst = cv2.warpAffine(img, M, (cols, rows))

plt.subplot(121)
plt.imshow(img)
plt.title('Input')
plt.subplot(122)
plt.imshow(dst)
plt.title('Output (Rotation)')
plt.show()

src_points = np.float32([[0, 0], [cols-1, 0], [0, rows-1]])
dst_points = np.float32([[cols-1, 0], [0, 0], [cols-1, rows-1]])

M = cv2.getAffineTransform(src_points, dst_points)
dst = cv2.warpAffine(img, M, (cols, rows))

plt.subplot(121)
plt.imshow(img)
plt.title('Input')
plt.subplot(122)
plt.imshow(dst)
plt.title('Output (Rotation - Mirror)')
plt.show()

kernel = np.ones((5, 5), np.uint8)

erosion = cv2.erode(img, kernel, iterations=1)
plt.subplot(121)
plt.imshow(img)
plt.title('Input')
plt.subplot(122)
plt.imshow(erosion)
plt.title('Output (Erosion)')
plt.show()

dilation = cv2.dilate(img, kernel, iterations=1)
plt.subplot(121)
plt.imshow(img)
plt.title('Input')
plt.subplot(122)
plt.imshow(dilation)
plt.title('Output (Dilation)')
plt.show()

opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
plt.subplot(121)
plt.imshow(img)
plt.title('Input')
plt.subplot(122)
plt.imshow(opening)
plt.title('Output (Opening)')
plt.show()

closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)
plt.subplot(121)
plt.imshow(img)
plt.title('Input')
plt.subplot(122)
plt.imshow(closing)
plt.title('Output (Closing)')
plt.show()

gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)
plt.subplot(121)
plt.imshow(img)
plt.title('Input')
plt.subplot(122)
plt.imshow(gradient)
plt.title('Output (Gradient)')
plt.show()

tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)
plt.subplot(121)
plt.imshow(img)
plt.title('Input')
plt.subplot(122)
plt.imshow(tophat)
plt.title('Output (Top Hat)')
plt.show()

blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)
plt.subplot(121)
plt.imshow(img)
plt.title('Input')
plt.subplot(122)
plt.imshow(tophat)
plt.title('Output (Black Hat)')
plt.show()
